server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com    #需要改c盘的映射文件hosts gateway-9527.com  127.0.0.1
    prefer-ip-address: true


zuul:
#  ignored-services: microservicecloud-dept
  #添加统一的前缀
  prefix: /chenshuhong
  ignored-services: "*"   #禁用所有原路径
  routes:
    #这里配置的是多个微服务的名称 跟访问的地址  自定义+serviceId ： 微服务名称   自定义+path ： 微服务地址
    mydept.serviceId: microservicecloud-dept
    #定义访问路径的地址
    mydept.path: /mydept/**

#访问的话就应该是前缀+访问地址 +方法名称   示例：http://gateway-9527.com:9527/chenshuhong/mydept/dept/get/1
info:
  app.name: chenshuhong-microcloud
  company.name: www.chenshuhong.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

